# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.VideoType'),
        ),
    ]
