# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('alt', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Image'),
            preserve_default=False,
        ),
    ]
