# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20160602_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
