# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20160602_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='campaign.Post'),
            preserve_default=False,
        ),
    ]
