# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_auto_20160612_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='projectimg/'),
        ),
    ]
