# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('so', 'Somali')], default='so', max_length=15),
        ),
    ]
