# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_post_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='images/None/no-image.png', upload_to='images/%Y/%m/%d'),
        ),
    ]
