# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_auto_20160628_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Video'),
        ),
    ]
