# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0023_auto_20160628_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_country', django_countries.fields.CountryField(max_length=2)),
                ('current_city', models.CharField(max_length=30)),
                ('region_of_birth', models.CharField(max_length=30)),
                ('city_of_birth', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
