# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region_of_birth',
            field=models.CharField(choices=[('Awdal', 'Awdal'), ('Bakool', 'Bakoo'), ('Banaadir', 'Banaadir'), ('Bari', 'Bari'), ('Bay', 'Bay'), ('Galguduud', 'Galguduud'), ('Gedo', 'Gedo'), ('Hiiraan', 'Hiiraan'), ('Jubada Dhexe', 'Jubada Dhexe'), ('Jubada Hoose', 'Jubada Hoose'), ('Nugaal', 'Nugaal'), ('Sanaag', 'Sanaag'), ('Shabeelaha Dhexe', 'Shabeelaha Dhexe'), ('Shabeelaha Hoose', 'Shabeelaha Hoose'), ('Sool', 'Sool'), ('Togdheer', 'Togdheer'), ('Waqooyi Galbeed', 'Waqooyi Galbeed')], max_length=30),
        ),
    ]
