# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0026_auto_20160703_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female')], max_length=10)),
                ('region_of_birth', models.CharField(blank=True, choices=[(b'Awdal', b'Awdal'), (b'Bakool', b'Bakoo'), (b'Banaadir', b'Banaadir'), (b'Bari', b'Bari'), (b'Bay', b'Bay'), (b'Galguduud', b'Galguduud'), (b'Gedo', b'Gedo'), (b'Hiiraan', b'Hiiraan'), (b'Jubada Dhexe', b'Jubada Dhexe'), (b'Jubada Hoose', b'Jubada Hoose'), (b'Nugaal', b'Nugaal'), (b'Sanaag', b'Sanaag'), (b'Shabeelaha Dhexe', b'Shabeelaha Dhexe'), (b'Shabeelaha Hoose', b'Shabeelaha Hoose'), (b'Sool', b'Sool'), (b'Togdheer', b'Togdheer'), (b'Waqooyi Galbeed', b'Waqooyi Galbeed')], max_length=30, null=True)),
                ('city_of_birth', models.CharField(max_length=30)),
                ('martial_status', models.CharField(choices=[(b'married', b'Married'), (b'single', b'Single')], max_length=30)),
                ('current_country', django_countries.fields.CountryField(max_length=2)),
                ('current_city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
