# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0027_auto_20160709_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='martial_status',
            new_name='marital_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
