# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0028_auto_20160709_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_city',
            new_name='city',
        ),
    ]
