# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0029_auto_20160709_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='city_of_residence',
        ),
    ]
