# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0034_auto_20160710_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_step',
            field=models.IntegerField(default=0),
        ),
    ]
