# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0035_auto_20160713_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.VideoType'),
        ),
    ]
